version: "3.8"
services:
  web:
    image: chivhor/final-project:latest
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"